#if defined _sm_menu_included
 #endinput
#endif
#define _sm_menu_included

#define INFO_MAX_SIZE 128
#define ITEM_MAX_SIZE 256

#define SPRAY_MANAGER "Spray manager"

#define ITEM_SPRAY_TRACE "Trace spray"
#define ITEM_SPRAY_REMOVE_QUICKLY "Remove spray quickly"
#define ITEM_SPRAY_REMOVE_ALL "Remove all sprays"
#define ITEM_SPRAY_REMOVE "Remove spray"
#define ITEM_SPRAY_DRAW "Draw spray"

#define ADMIN_MENU "adminmenu"
